name: incognita
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9

  # Core requirements
  - geopandas>=0.8
  - numpy
  - pandas
  - shapely
  - pyarrow
  - pygeos>=0.10
  - toml
  - pydantic

  # Testing
  - pytest
  - hypothesis

