[census_extract]
original = "data/Scout Census Data/Census 2020 Extract (1).csv"
merged = "data/Scout Census Data/Census 2020 Extract (1) with May 2019 fields crown deps.feather"

[ons_pd]
full = "data/ONSPD_MAY_2019_UK/Data/ONSPD_MAY_2019_UK.csv"
reduced = "data/ONSPD_MAY_2019_UK/Data/ONSPD_MAY_2019_UK reduced counties.feather"
minified = "data/ONSPD_MAY_2019_UK/Data/ONSPD_MAY_2019_UK-minified-old.feather"
reduced_nystest = "data/ons_pd_with_nys2.csv"

[folders]
# Folder within the ONS Postcode Directory archive holding names and codes files
ons_pd_names_codes = "data/ONSPD_MAY_2019_UK/Documents/"
# Folder for national statistical data (age profiles etc)
national_statistical = "data/National Statistical data/"
# Folder with all shapefiles
boundaries = "data/Boundary shape files/"
# Folder for generated files
output = "Output/"

[ons2019."lad"]
name = "oslaua"  # Local Authority Districts

codes.path = "LA_UA names and codes UK as at 12_19.csv"
codes.key = "LAD19CD"
codes.key_type = "string"
codes.name = "LAD19NM"

shapefile.path = "Local_Authority_Districts__December_2019__Boundaries_UK_BUC/Local_Authority_Districts__December_2019__Boundaries_UK_BUC.shp"
shapefile.key = "lad19cd"
shapefile.name = "lad19nm"

age_profile.path = "lad_by_age.csv"
age_profile.key = "Code"

[ons2019."cty"]
name = "oslaua"  # Counties

codes.path = "LA_UA names and codes UK as at 12_19.csv"
codes.key = "LAD19CD"
codes.key_type = "string"
codes.name = "LAD19NM"

shapefile.path = "Counties_and_Unitary_Authorities_December_2017_Generalised_Clipped_Boundaries_in_UK/Counties_and_Unitary_Authorities_December_2017_Generalised_Clipped_Boundaries_in_UK.shp"
shapefile.key = "ctyua17cd"
shapefile.name = "ctyua17nm"

[ons2019."osward"]
name = "osward"  # Council Wards

codes.path = "Ward names and codes UK as at 05_19_NSPD.csv"
codes.key = "WD19CD"
codes.key_type = "string"
codes.name = "WD19NM"

shapefile.path = "Wards_December_2019_Boundaries_UK_BGC/Wards_December_2019_Boundaries_UK_BGC.shp"
shapefile.key = "WD19CD"
shapefile.name = "WD19NM"

age_profile.path = "osward_by_age_mid_2018_population_may_2019_wards.csv"
age_profile.key = "Ward Code"

[ons2019."pcon"]
name = "pcon"  # Parliamentary Constituencies

codes.path = "Westminster Parliamentary Constituency names and codes UK as at 12_14.csv"
codes.key = "PCON14CD"
codes.key_type = "string"
codes.name = "PCON14NM"

shapefile.path = "Westminster_PCON_Dec_2017_Generalised_Clipped_UK/Westminster_Parliamentary_Constituencies_December_2017_Generalised_Clipped_Boundaries_in_the_UK.shp"
shapefile.key = "pcon17cd"
shapefile.name = "pcon17nm"

age_profile.path = "pcon_by_age.csv"
age_profile.key = "PCON11CD"

[ons2019."lsoa"]
name = "lsoa11"  # Lower Level Super Output Areas

codes.path = "LSOA (2011) names and codes UK as at 12_12.csv"
codes.key = "LSOA11CD"
codes.key_type = "string"
codes.name = "LSOA11NM"

shapefile.path = "Lower_Layer_Super_Output_Areas_December_2011_Boundaries_EW_BSC/Lower_Layer_Super_Output_Areas_December_2011_Boundaries_EW_BSC.shp"
shapefile.key = "LSOA11CD"
shapefile.name = "LSOA11NM"

[ons2019."msoa"]
name = "msoa11"  # Middle Layer Super Output Areas

codes.path = "MSOA (2011) names and codes UK as at 12_12.csv"
codes.key = "MSOA11CD"
codes.key_type = "string"
codes.name = "MSOA11NM"

shapefile.path = "Middle_Layer_Super_Output_Areas_December_2011_Full_Clipped_Boundaries_in_England_and_Wales/Middle_Layer_Super_Output_Areas_December_2011_Full_Clipped_Boundaries_in_England_and_Wales.shp"
shapefile.key = "msoa11cd"
shapefile.name = None

[ons2019."iz"]
name = "msoa11"  # Intermediate Zones (codepages identical to MSOA but different shapefiles)

codes.path = "MSOA (2011) names and codes UK as at 12_12.csv"
codes.key = "MSOA11CD"
codes.key_type = "string"
codes.name = "MSOA11NM"

shapefile.path = "SG_IntermediateZoneBdry_2011/SG_IntermediateZone_Bdry_2011.shp"
shapefile.key = "InterZone"
shapefile.name = None

[custom_boundaries."District"]
name = "D_ID"

codes.path = "data/Scout Census Data/district_id_mapping.csv"
codes.key = "D_ID"
codes.key_type = "Int32"
codes.name = "D_name"

shapefile.path = "../../scripts/districts_buffered.geojson"
shapefile.key = "id"
shapefile.name = "name"

[custom_boundaries."imd_decile"]
name = "imd_decile"

codes.path = "data/Scout Census Data/imd_names_and_codes.csv"
codes.key = "IMD Decile"
codes.key_type = "Int32"
codes.name = "Name"

[custom_boundaries."NYS"]
name = "nys_districts"

codes.path = "data/Scout Census Data/North_Yorkshire_Districts.csv"
codes.key = "ID"
codes.key_type = "string"
codes.name = "District"

shapefile.path = "North_Yorkshire_Districts/North_Yorkshire_Districts.shp"
shapefile.key = "id"
shapefile.name = "district"

age_profile.path = "age_by_lsoa_mid_2017_total.csv"
age_profile.key = "Area Codes"
age_profile.pivot_key = "lsoa11"

[custom_boundaries."County"]
name = "ctyua19cd"

codes.path = "Scout Census Data/Counties_and_Unitary_Authorities__December_2019__Boundaries_UK.csv"
codes.key = "ctyua19cd"
codes.key_type = "string"
codes.name = "ctyua19nm"

shapefile.path = "Counties_UAs_Dec_2019_BUC_and_GADM36_crown_dependencies/Counties_UAs_Dec_2019_BUC_and_GADM36_crown_dependencies.shp"
shapefile.key = "ctyua19cd"
shapefile.name = "ctyua19nm"

age_profile.path = "age_by_lsoa_mid_2017_total.csv"
age_profile.key = "Area Codes"
age_profile.pivot_key = "lsoa11"
