name: testing

on:
  pull_request:
  push:
    branches: [master]

jobs:
  testing-pip:
    name: Testing using pip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache pip files
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pytest-cov, codecov
        run: |
          pip install pytest-cov codecov

      - name: Test with pytest, generate coverage report
        run: |
          python -m pytest --cov=./

      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v1

  testing-conda:
    name: Testing using conda (mambaforge)
    runs-on: ubuntu-latest
    defaults:
      run:
        # https://github.com/conda-incubator/setup-miniconda#use-a-default-shell
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Cache conda files
        uses: actions/cache@v2
        with:
          path: |
            ~/conda_pkgs_dir
            /opt/hostedtoolcache/Mambaforge
          key:
            ${{ runner.os }}-mambaforge-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-mambaforge-

      - name: Setup Miniconda (Mambaforge)
        uses: conda-incubator/setup-miniconda@master
        with:
          activate-environment: scouts_mapping
          environment-file: environment.yml
          channel-priority: strict
          # Mamba:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          # This needs to be set for caching to work properly
          use-only-tar-bz2: true

      - name: Test with pytest
        run: |
          python -m pytest
